Added quote from Melina Marchetta
jayehernandez/letra-extension pull request #327
Opened 2020-10-01 17:33 UTC by Kryze

## ✅ New Quote Checklist
- [x] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [x] The quote(s) added are about **learning a foreign language**.
- [x] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

2020-10-01 17:43 UTC, Kvaibhav01 requested changes
Thanks for the PR, just make the necessary changes as shown.

2020-10-01 17:43 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "author":"Melina Marchetta",
Please add a space between the key and its value as shown:

```suggestion
    "author": "Melina Marchetta",
```

2020-10-01 17:43 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "sentence":"Because without our language, we have lost ourselves. Who are we without our words?"
The same goes for this.

2020-10-03 17:19 UTC, jayehernandez requested changes
Same comments as @Kvaibhav01! Please request for review after making the necessary changes!

2020-12-12 15:30 UTC, jayehernandez commented
Closing this stale PR :)

2020-12-12 15:30 UTC, closed without merging