added a new quote
jayehernandez/letra-extension pull request #338
Opened 2020-10-02 14:43 UTC by Khush-Ramdev

## ✅ New Quote Checklist
- [ x ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [ x ] The quote(s) added are about **learning a foreign language**.
- [ x ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ x ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

2020-10-02 14:46 UTC, Kvaibhav01 requested changes

2020-10-02 14:46 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "sentence":"Some Say latin is a dead language but I say its just taking a long nap."
Thanks for the PR. Please update it as shown:

```suggestion
    "sentence": "Some Say latin is a dead language but I say its just taking a long nap." 
```

2020-10-04 01:08 UTC, jayehernandez requested changes

2020-10-04 01:08 UTC, jayehernandez commented on server/data/quotes.json
> +    "sentence": "Some Say latin is a dead language but I say its just taking a long nap."
Please add these improvements

```suggestion
    "sentence": "Some say Latin is a dead language but I say it's just taking a long nap." 
```

2020-10-04 01:08 UTC, jayehernandez commented on server/data/quotes.json
> +    "author": "Amy Santiago",
```suggestion
    "author": "Amy Santiago in Brooklyn Nine Nine",
```

2020-10-04 11:47 UTC, jayehernandez approved these changes

2020-10-04 11:47 UTC, jayehernandez commented
Thank you for contributing to Letra ☀️, @Khush-Ramdev!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

2020-10-04 11:47 UTC, merged