Update quotes.json : Add a quote by Anshuman
jayehernandez/letra-extension pull request #340
Opened 2020-10-02 16:26 UTC by AvDevx

## ✅ New Quote Checklist
- [ ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [ ] The quote(s) added are about **learning a foreign language**.
- [ ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

## ✅ New Language Checklist
- [ ] There is ❌ no assigned issue or pull request for this new language.
- [ ] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [ ] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [ ] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** attribute for appropriate languages.
- [ ] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [ ] Removed duplicates and noted 🗒 them in the Pull Request.
- [ ] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [ ] Add new language in `README.md`

2020-10-02 17:40 UTC, Kvaibhav01 requested changes
Thanks for the PR @AvDevx, please change as suggested.

2020-10-02 17:40 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "author": "Anshuman vats",
```suggestion
    "author": "Anshuman Vats",
```

2020-10-02 17:48 UTC, Kvaibhav01 commented
Thanks for updating this!

2020-10-02 17:49 UTC, AvDevx reviewed
Is this okay? @Kvaibhav01 
Sorry very new to this don't have much idea how this works.

2020-10-02 17:50 UTC, Kvaibhav01 commented
You did good @AvDevx, keep it up 👍

2020-10-02 17:52 UTC, AvDevx commented
> You did good @AvDevx, keep it up 👍

2020-10-02 17:59 UTC, AvDevx commented
Sorry to bother you is there anything else I need to do here or I can move to next issue?

2020-10-02 18:00 UTC, Kvaibhav01 commented
It's done here @AvDevx, your PR will be accepted and merged soon. Feel free to work on other issues.

2020-10-04 01:15 UTC, jayehernandez commented
Thank you for contributing to Letra ☀️, @AvDevx!! Went ahead and resolved the merge conflicts too. Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

2020-10-04 01:15 UTC, merged

2020-10-04 21:18 UTC, AvDevx commented
@Kvaibhav01 This is not accepted for hacktoberfest right?