added quotes, french authors
jayehernandez/letra-extension pull request #341
Opened 2020-10-02 17:10 UTC by Vlad412

Hello,
Added two quotes from french authors, Ferdinand de Saussure and Valery Giscard D'Estaing.
Hope it helps 🤷‍♂️
Have a nice day 🙏

## ✅ New Quote Checklist
- [ x] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [x ] The quote(s) added are about **learning a foreign language**.
- [x ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

2020-10-02 17:42 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "author": "Valery Giscard D'Estaing",
Add this quote alphabetically towards the "V" letter quotes.

2020-10-02 17:43 UTC, Kvaibhav01 requested changes
Thanks for the PR @Vlad412. Kindly change it as requested in the comment.

2020-10-02 17:55 UTC, Kvaibhav01 commented
Thanks for the change!

2020-10-02 17:56 UTC, Vlad412 commented
here you go 🙏
thanks and have a nice day

2020-10-04 01:10 UTC, jayehernandez commented
Thank you for contributing to Letra ☀️, @Vlad412!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

2020-10-04 01:10 UTC, merged