Added two new quotes
jayehernandez/letra-extension pull request #343
Opened 2020-10-02 18:57 UTC by RaithZx

## ✅ New Quote Checklist
- [x ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [x ] The quote(s) added are about **learning a foreign language**.
- [x ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

This PR references #13

2020-10-03 08:36 UTC, Kvaibhav01 requested changes
Thanks for the PR @RaithZx. Please update as suggested.

2020-10-03 08:36 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "sentence": "Good writers are good readers and listeners."
This quote is not related to "learning a foreign language" or something about language. Please change it. It doesn't meet the [requirements](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_quote.md#-checklist).

2020-10-11 03:41 UTC, jayehernandez requested changes
Forgot to request changes, please refer to @Kvaibhav01's comment for changes needed.

2020-12-12 15:31 UTC, jayehernandez commented
Closing stale PR

2020-12-12 15:31 UTC, closed without merging