Add Some Quotes about Language
jayehernandez/letra-extension pull request #350
Opened 2020-10-03 04:43 UTC by rizastoday

## ✅ New Quote Checklist
- [ ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [ ] The quote(s) added are about **learning a foreign language**.
- [ ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

## ✅ New Language Checklist
- [ ] There is ❌ no assigned issue or pull request for this new language.
- [ ] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [ ] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [ ] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** attribute for appropriate languages.
- [ ] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [ ] Removed duplicates and noted 🗒 them in the Pull Request.
- [ ] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [ ] Add new language in `README.md`

2020-10-03 04:48 UTC, rizastoday commented
Hi @jayehernandez , this is my first contribution to an open-source project, please review it and give feedback if needed, I will be very enthusiastic,big thank you

2020-10-04 04:52 UTC, jayehernandez requested changes
Hey there @rizastoday! Congrats on your first contribution! Please add the quotes in alphabetical order, based on the author's first name. When that's done, you may see that some of the quotes you added are already duplicates, hope you can remove those.

Please request for review again, once done.

2020-10-05 03:30 UTC, rizastoday commented
Hi there @jayehernandez , I've made a few changes such as sorting by author's first name and deleting the duplicate quotes that I previously added. Please re-review and let me know if there any of my changes go wrong. Thank you

2020-10-05 13:11 UTC, jayehernandez requested changes

2020-10-05 13:11 UTC, jayehernandez commented on server/data/quotes.json
> +    "sentence": "In the language of meditation, the past is past, the future is not here, now is the only gift available"
Hope you can remove this quote as it is not about learning a foreign language.

2020-10-05 13:11 UTC, jayehernandez commented on server/data/quotes.json
> +    "author": "French Proverb 2020",
Remove the 2020 in the author name :)

2020-10-05 13:11 UTC, jayehernandez commented on server/data/quotes.json
> +    "sentence": "Leaders must be practical and realistic, but must speak visionary and idealistic language"
Quote is also unrelated, hope you can remove this!

2020-10-05 13:12 UTC, jayehernandez commented
Thanks for re-arranging them @rizastoday, just have a few more comments and PR is good to go. Hope you can resolve conflicts too.

2020-10-05 13:54 UTC, rizastoday commented
I've made some changes regarding removing some unrelated quotes and I've tried to remove the conflict too. Hope you review it @jayehernandez  thank you

2020-10-09 11:07 UTC, jayehernandez approved these changes

2020-10-09 11:08 UTC, jayehernandez commented
Thank you for contributing to Letra ☀️, @rizastoday!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

2020-10-09 11:08 UTC, merged