Added new quote by Swami Vivekananda
jayehernandez/letra-extension pull request #352
Opened 2020-10-03 08:28 UTC by reachtokish

## ✅ New Quote Checklist
- [x] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [x] The quote(s) added are about **learning a foreign language**.
- [x] The sentence attribute does not have inner quotation marks and is ended with a period.
- [x ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

2020-10-03 08:57 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "author": "Swami Vivekananda",
Please add it alphabetically under the quotes starting with the author name of "S".

2020-10-03 08:57 UTC, Kvaibhav01 requested changes
Hey @reachtokish thanks for the PR, update the changes as requested.

2020-10-03 09:16 UTC, reachtokish commented
> Hey @reachtokish thanks for the PR, update the changes as requested.

Done. Sorry I missed that part.

2020-10-04 04:53 UTC, merged

2020-10-04 04:53 UTC, jayehernandez commented
Thank you for contributing to Letra ☀️, @reachtokish!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)