Added a new quote
jayehernandez/letra-extension pull request #416
Opened 2020-10-09 04:27 UTC by UdithaIshan

## ✅ New Quote Checklist
- [x] The quote(s) added are in alphabetical order by author's first name and not ❌ duplicates.
- [x] The quote(s) added are about **learning a foreign language**.
- [x] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

2020-10-09 07:19 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "sentence": "To learn to read is to light a fire, every syllable that is spelling out is a spark."
This quote isn't acceptable. we need quotes based on "learning a foreign language" or close to this.

2020-10-09 07:19 UTC, Kvaibhav01 requested changes
Please update the quote as suggested.

2020-10-09 07:40 UTC, UdithaIshan commented
@Kvaibhav01, sorry for the misunderstanding. I've changed that. please review.

2020-10-09 17:51 UTC, kvharish approved these changes

2020-10-11 03:42 UTC, jayehernandez approved these changes
Thank you for contributing to Letra ☀️, @UdithaIshan!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

2020-10-11 03:42 UTC, merged