Add a quote by Johann Wolfgang von Goethe
jayehernandez/letra-extension pull request #471
Opened 2020-10-18 14:57 UTC by mkhy19

Added a quote by Johann Wolfgang von Goethe.

## ✅ New Quote Checklist
- [x] The quote(s) added are in alphabetical order by author's first name and not ❌ duplicates.
- [x] The quote(s) added are about **learning a foreign language**.
- [x] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

2020-10-18 17:44 UTC, Kvaibhav01 requested changes
This is a [duplicate quote](https://github.com/jayehernandez/letra-extension/blob/08226428a914bb75266e566bad4ad86056bab92e/server/data/quotes.json#L403) and doesn't align with our contribution guidelines. Please update it.

2020-10-18 18:16 UTC, mkhy19 commented
I updated it @Kvaibhav01

2020-10-18 18:22 UTC, Kvaibhav01 requested changes

2020-10-18 18:22 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "sentence": "“Meow” means “woof” in cat.”"
It doesn't match the contribution requirement. We need quotes regarding "learning a foreign language" or similar. You need to change it.

2020-10-18 18:46 UTC, mkhy19 commented
It was hard to find a quote about learning a language but finally I found it LOL, Hope you accept it.

2020-10-18 18:53 UTC, Kvaibhav01 reviewed
Update as required.

2020-10-18 18:53 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "author": "Dutch Proverb",
Please add it alphabetically as others are. Read the [contribution guidelines checklist](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_quote.md#-checklist) carefully before submitting the PR.

2020-10-18 18:53 UTC, Kvaibhav01 commented on server/data/quotes.json
> +    "sentence": "Who knows the language is at home everywhere.”"
No need of adding another quote symbol at the end of the sentence.

```suggestion
    "sentence": "Who knows the language is at home everywhere."
```

2020-10-19 09:47 UTC, mkhy19 commented
DONE @Kvaibhav01

2020-10-19 11:19 UTC, Kvaibhav01 commented
It's still not correct. You need to arrange it alphabetically with the author's name as written in the guidelines.

2020-10-19 12:25 UTC, mkhy19 commented
Done again, LOL

2020-10-21 12:56 UTC, jayehernandez commented
Thank you for contributing to Letra ☀️, @mkhy19!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

2020-10-21 12:56 UTC, merged